# Generated by Django 3.1.2 on 2020-10-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
